# Creates a new image version when a new version of the devvm.json file is created.
name: Prebuild 2

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  workflow_dispatch:
    
jobs:
  create-prebuild:
    name: Create prebuild
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"

      - name: Queue request
        env:
          ENDPOINT: ${{github.api_url}}/vscs_internal/user/${{github.actor}}/codespaces
          TOKEN: ${{github.token}}
          REPO_ID: ${{github.repository.id}}
          REF: ${{github.ref}}
          LOCATION: WestUs2
          SKU_NAME: standardLinux32gb
        run: |
          curl "$ENDPOINT" --anyauth --verbose \
             -H 'Content-Type: application/json' \
             -H 'Authorization: Bearer $TOKEN' \
             --data-raw '{
               "repository_id": $REPO_ID,
               "ref": "$REF",
               "location": "$LOCATION",
               "sku_name": "$SKU_NAME"
             }'
