# Creates a new image version when a new version of the devvm.json file is created.
name: Prebuild 2

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  workflow_dispatch:
    
jobs:
  create-prebuild:
    name: Create prebuild
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"

      - name: Queue request
        shell: powershell
        run: |
          $url = "${{github.api_url}}/vscs_internal/user/${{github.actor}}/codespaces";
          $headers = @{ 'Authorization' = ("Bearer ${{secrets.GHCS_TOKEN}}") };
          $body = @"
          {
              "repository_id": ${{github.event.repository.id}},
              "ref": "${{github.ref}}",
              "location": "WestUs2",
              "sku_name": "standardLinux32gb"
          }
          "@;
          Invoke-RestMethod -Uri $url -Headers $headers -Method Post -Body $body;
