# Creates a new image version when a new version of the devvm.json file is created.
name: Prebuild

# Run the workflow only when the devvm.json file has been updated in the master branch.
on:
  workflow_dispatch:
    
jobs:
  create-prebuild:
    name: Create prebuild
    runs-on: windows-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{toJSON(github)}}
        run: echo "$GITHUB_CONTEXT"

      - name: Queue request
        shell: powershell
        run: |
          $url = '${{secrets.CS_ENDPOINT}}';
          $headers = @{ 'Authorization' = ("GitHub ${{secrets.GHCS_TOKEN}}") };
          $body = @"
          {
            "Type": "CloudEnvironment",
            "FriendlyName": "${{github.sha}}",
            "Seed": {
              "type": "Git",
              "moniker": "${{github.event.repository.html_url}}"
            },
            "SkuName": "standardLinux32gb",
            "PlanId": "${{secrets.PLAN_ID}}",
            "AutoShutdownDelayMinutes": 240,
            "CreateAsPrebuild": true
          }
          "@;
          Invoke-RestMethod -Uri $url -Method Post -Headers $headers -ContentType 'application/json' -Body $body;
